// GENERATED by scripts/gen-agent-icons.mjs — do not edit by hand.
// Herdr agent name -> logo file in media/agent-logos ("mono" logos ship as <file>-light.svg / <file>-dark.svg).

export interface AgentLogo {
  file: string;
  mono: boolean;
}

export const AGENT_LOGOS: Record<string, AgentLogo> = {
  claude: { file: 'claude-color', mono: false },
  codex: { file: 'codex-color', mono: false },
  openai: { file: 'openai', mono: true },
  kiro: { file: 'kiro-color', mono: false },
  cursor: { file: 'cursor', mono: true },
  copilot: { file: 'githubcopilot', mono: true },
  gemini: { file: 'gemini-color', mono: false },
  qwen: { file: 'qwen-color', mono: false },
  kimi: { file: 'kimi', mono: true },
  devin: { file: 'devin-color', mono: false },
  grok: { file: 'grok', mono: true },
  opencode: { file: 'opencode', mono: true },
  kilo: { file: 'kilocode', mono: true },
  hermes: { file: 'nousresearch', mono: true },
  qodercli: { file: 'qoder-color', mono: true },
  qoder: { file: 'qoder-color', mono: true },
  mastracode: { file: 'mastra', mono: true },
  antigravity_cli: { file: 'antigravity-color', mono: false },
  antigravity: { file: 'antigravity-color', mono: false },
  agy: { file: 'antigravity-color', mono: false },
  pi: { file: 'pi', mono: true },
  amp: { file: 'amp-color', mono: false },
  goose: { file: 'goose', mono: true },
  junie: { file: 'junie-color', mono: false },
  trae: { file: 'trae-color', mono: false },
  roo: { file: 'roocode', mono: true },
  cline: { file: 'cline', mono: true },
  windsurf: { file: 'windsurf', mono: true },
  mistral: { file: 'mistral-color', mono: false },
  vibe: { file: 'mistral-color', mono: false },
};

/** "claude" / "claude-code" / "antigravity_cli" -> logo, or undefined for agents without one. */
export function agentLogo(kind?: string): AgentLogo | undefined {
  const k = (kind ?? '').toLowerCase();
  return k ? (AGENT_LOGOS[k] ?? AGENT_LOGOS[k.split(/[^a-z0-9]/)[0]]) : undefined;
}
