// GENERATED by scripts/gen-herdr-types.mjs from `herdr api schema --json` — do not edit by hand.
// herdr 0.9.1 · protocol 22 · schema_version 1
// Regenerate after upgrading Herdr: npm run gen:types

export const HERDR_PROTOCOL = 22;

export interface SessionSnapshotResult {
  snapshot: SessionSnapshot;
  type: 'session_snapshot';
}

export interface PaneProcessInfoResult {
  process_info: PaneProcessInfo;
  type: 'pane_process_info';
}

export interface PaneReadResponse {
  read: PaneReadResult;
  type: 'pane_read';
}

export interface WorkspaceCreatedResult {
  root_pane: PaneInfo;
  tab: TabInfo;
  type: 'workspace_created';
  workspace: WorkspaceInfo;
}

export interface TabCreatedResult {
  root_pane: PaneInfo;
  tab: TabInfo;
  type: 'tab_created';
}

export interface WorktreeCreatedResult {
  root_pane: PaneInfo;
  tab: TabInfo;
  type: 'worktree_created';
  workspace: WorkspaceInfo;
  worktree: WorktreeInfo;
}

export interface WorktreeRemovedResult {
  forced: boolean;
  path: string;
  type: 'worktree_removed';
  workspace_id: string;
}

export interface AgentStartedResult {
  agent: AgentInfo;
  argv: string[];
  type: 'agent_started';
}

export interface OkResult {
  type: 'ok';
}

export interface SessionSnapshot {
  agents: AgentInfo[];
  focused_pane_id?: string | null;
  focused_tab_id?: string | null;
  focused_workspace_id?: string | null;
  layouts: PaneLayoutSnapshot[];
  panes: PaneInfo[];
  /** format: uint32 */
  protocol: number;
  tabs: TabInfo[];
  version: string;
  workspaces: WorkspaceInfo[];
}

export interface PaneProcessInfo {
  /** format: uint32 */
  foreground_process_group_id?: number | null;
  foreground_processes?: PaneProcessInfoProcess[];
  pane_id: string;
  /** format: uint32 */
  shell_pid?: number | null;
  tty?: string | null;
}

export interface PaneReadResult {
  format: ReadFormat;
  pane_id: string;
  /** format: uint64 */
  revision: number;
  source: ReadSource;
  tab_id: string;
  text: string;
  truncated: boolean;
  workspace_id: string;
}

export interface WorkspaceCreateParams {
  cwd?: string | null;
  env?: Record<string, string>;
  /** default: false */
  focus?: boolean;
  label?: string | null;
  /** Workspace whose focused pane supplies the `follow` cwd policy. */
  source_workspace_id?: string | null;
}

export interface WorkspaceRenameParams {
  label: string;
  workspace_id: string;
}

export interface WorkspaceCloseParams {
  close_group?: boolean;
  workspace_id: string;
}

export interface WorktreeCreateParams {
  base?: string | null;
  branch?: string | null;
  cwd?: string | null;
  /** default: false */
  focus?: boolean;
  label?: string | null;
  path?: string | null;
  trust_repository?: boolean;
  workspace_id?: string | null;
}

export interface WorktreeRemoveParams {
  /** default: false */
  force?: boolean;
  trust_repository?: boolean;
  workspace_id: string;
}

export interface TabCreateParams {
  cwd?: string | null;
  env?: Record<string, string>;
  /** default: false */
  focus?: boolean;
  label?: string | null;
  workspace_id?: string | null;
}

export interface TabRenameParams {
  label: string;
  tab_id: string;
}

export interface TabTarget {
  tab_id: string;
}

export interface AgentStartParams {
  args?: string[];
  kind: string;
  name: string;
  pane_id: string;
  /** Startup timeout in milliseconds. Values must be greater than 3000 and at most 300000. · format: uint64 */
  timeout_ms?: number | null;
}

export interface PaneRenameParams {
  label?: string | null;
  pane_id: string;
}

export interface PaneTarget {
  pane_id: string;
}

export interface AgentRenameParams {
  name?: string | null;
  target: string;
}

export interface PaneInfo {
  agent?: string | null;
  agent_session?: AgentSessionInfo | null;
  agent_status: AgentStatus;
  cwd?: string | null;
  display_agent?: string | null;
  focused: boolean;
  foreground_cwd?: string | null;
  label?: string | null;
  pane_id: string;
  /** format: uint64 */
  revision: number;
  scroll?: PaneScrollInfo | null;
  state_labels?: Record<string, string>;
  tab_id: string;
  terminal_id: string;
  terminal_title?: string | null;
  terminal_title_stripped?: string | null;
  title?: string | null;
  tokens?: Record<string, string>;
  workspace_id: string;
}

export interface TabInfo {
  agent_status: AgentStatus;
  focused: boolean;
  label: string;
  /** format: uint */
  number: number;
  /** format: uint */
  pane_count: number;
  tab_id: string;
  workspace_id: string;
}

export interface WorkspaceInfo {
  active_tab_id: string;
  agent_status: AgentStatus;
  focused: boolean;
  label: string;
  /** format: uint */
  number: number;
  /** format: uint */
  pane_count: number;
  /** format: uint */
  tab_count: number;
  tokens?: Record<string, string>;
  workspace_id: string;
  worktree?: WorkspaceWorktreeInfo | null;
}

export interface WorktreeInfo {
  branch?: string | null;
  is_bare: boolean;
  is_detached: boolean;
  is_linked_worktree: boolean;
  is_prunable: boolean;
  label: string;
  open_workspace_id?: string | null;
  path: string;
}

export interface AgentInfo {
  agent?: string | null;
  agent_session?: AgentSessionInfo | null;
  agent_status: AgentStatus;
  cwd?: string | null;
  display_agent?: string | null;
  focused: boolean;
  foreground_cwd?: string | null;
  interactive_ready?: boolean;
  launch_pending?: boolean;
  name?: string | null;
  pane_id: string;
  /** format: uint64 */
  revision: number;
  screen_detection_skipped?: boolean;
  /** format: uint64 · default: 0 */
  state_change_seq?: number;
  state_labels?: Record<string, string>;
  tab_id: string;
  terminal_id: string;
  terminal_title?: string | null;
  terminal_title_stripped?: string | null;
  title?: string | null;
  tokens?: Record<string, string>;
  workspace_id: string;
}

export interface PaneLayoutSnapshot {
  area: PaneLayoutRect;
  focused_pane_id: string;
  panes: PaneLayoutPane[];
  splits: PaneLayoutSplit[];
  tab_id: string;
  workspace_id: string;
  zoomed: boolean;
}

export interface PaneProcessInfoProcess {
  argv?: string[] | null;
  argv0?: string | null;
  cmdline?: string | null;
  cwd?: string | null;
  name: string;
  /** format: uint32 */
  pid: number;
}

export type ReadFormat = 'text' | 'ansi';

export type ReadSource = 'visible' | 'recent' | 'recent_unwrapped' | 'detection';

export interface AgentSessionInfo {
  agent: string;
  kind: AgentSessionRefKind;
  source: string;
  value: string;
}

export type AgentStatus = 'idle' | 'working' | 'blocked' | 'done' | 'unknown';

export interface PaneScrollInfo {
  /** format: uint64 */
  max_offset_from_bottom: number;
  /** format: uint64 */
  offset_from_bottom: number;
  /** format: uint64 */
  viewport_rows: number;
}

export interface WorkspaceWorktreeInfo {
  checkout_path: string;
  is_linked_worktree: boolean;
  repo_key: string;
  repo_name: string;
  repo_root: string;
}

export interface PaneLayoutRect {
  /** format: uint16 */
  height: number;
  /** format: uint16 */
  width: number;
  /** format: uint16 */
  x: number;
  /** format: uint16 */
  y: number;
}

export interface PaneLayoutPane {
  focused: boolean;
  pane_id: string;
  rect: PaneLayoutRect;
}

export interface PaneLayoutSplit {
  direction: SplitDirection;
  id: string;
  /** format: float */
  ratio: number;
  rect: PaneLayoutRect;
}

export type AgentSessionRefKind = 'id' | 'path';

export type SplitDirection = 'right' | 'down';
